name: Deploy Backend to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH key (.pem format)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/ec2-key.pem
          chmod 600 ~/.ssh/ec2-key.pem
          echo "Connecting to ${{ secrets.EC2_HOST }}"
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts || true
      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/ec2-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            mkdir -p ~/hms/hms-backend
            cd ~/hms/hms-backend
            if [ ! -d ".git" ]; then
              git clone https://github.com/AiswaryaCp/hms-backend.git .
            else
              git pull
            fi
            docker stop hms-backend || true
            docker rm hms-backend || true
            docker build -t hms-backend .
            docker run -d --name hms-backend -p 8000:8000 hms-backend
          EOF
