name: Deploy Backend to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            cd ~/hms/hms-backend || mkdir -p ~/hms/hms-backend && cd ~/hms/hms-backend
            git clone https://github.com/AiswaryaCp/hms-backend.git . || git pull
            docker stop hms-backend || true
            docker rm hms-backend || true
            docker build -t hms-backend .
            docker run -d --name hms-backend -p 8000:8000 hms-backend
            # Run migrations inside the container
            docker exec hms-backend python manage.py migrate
          EOF
